// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB69DTM-dXWLXzZMnm6i1m1Cd2zZw49A1o',
    appId: '1:106851791798:web:5c4058cf086f3d66d4c717',
    messagingSenderId: '106851791798',
    projectId: 'k9ops-259ff',
    authDomain: 'k9ops-259ff.firebaseapp.com',
    databaseURL: 'https://k9ops-259ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'k9ops-259ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHXUwadUrcg2rDc3btfvqShgEKTiBXukA',
    appId: '1:106851791798:android:e01e327dde88d9a9d4c717',
    messagingSenderId: '106851791798',
    projectId: 'k9ops-259ff',
    databaseURL: 'https://k9ops-259ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'k9ops-259ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASGF53_yZxh9NWgqbU8A6r8ni9ttGVfUo',
    appId: '1:106851791798:ios:45e467c5bbb50918d4c717',
    messagingSenderId: '106851791798',
    projectId: 'k9ops-259ff',
    databaseURL: 'https://k9ops-259ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'k9ops-259ff.firebasestorage.app',
    iosBundleId: 'com.example.board',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASGF53_yZxh9NWgqbU8A6r8ni9ttGVfUo',
    appId: '1:106851791798:ios:45e467c5bbb50918d4c717',
    messagingSenderId: '106851791798',
    projectId: 'k9ops-259ff',
    databaseURL: 'https://k9ops-259ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'k9ops-259ff.firebasestorage.app',
    iosBundleId: 'com.example.board',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB69DTM-dXWLXzZMnm6i1m1Cd2zZw49A1o',
    appId: '1:106851791798:web:5244d8465d69858dd4c717',
    messagingSenderId: '106851791798',
    projectId: 'k9ops-259ff',
    authDomain: 'k9ops-259ff.firebaseapp.com',
    databaseURL: 'https://k9ops-259ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'k9ops-259ff.firebasestorage.app',
  );
}
